Update Vault Manager Documentation
braintree/braintree-web-drop-in pull request #800
Opened 2022-02-08 16:06 UTC by jaxdesmarais

### Summary

Updates the JSDoc for vault manager to reflect the current behavior of what happens if you do not pass `options.defaultFirst`.

### Checklist

- [x] Added a changelog entry

### Authors
> List GitHub usernames for everyone who contributed to this pull request.

- @Epreuve @jaxdesmarais

2022-02-08 20:30 UTC, sshropshire approved these changes

2022-02-09 16:31 UTC, crookedneighbor requested changes

2022-02-09 16:31 UTC, crookedneighbor commented on CHANGELOG.md
> +  - Clarify `options.showDefaultPaymentMethodFirst` functionality in JSDoc
we don't typically add a changelog for docs updates.

2022-02-09 16:31 UTC, crookedneighbor commented on src/index.js
> + * @param {boolean} [options.showDefaultPaymentMethodFirst=true] When `true` or left out, the customer's default payment method will be displayed first in the list of vaulted payment methods. When `f
I'd be just a little more explicit about what is happening.

```suggestion
 * @param {boolean} [options.showDefaultPaymentMethodFirst=true] When `true` or left out, the customer's default payment method will be displayed first in the list of vaulted payment methods. When `false`, the order of the displayed payment methods is not guaranteed. Only applicable when using a [client token with a customer id](https://developers.braintreepayments.com/reference/request/client-token/generate/#customer_id) and a customer with saved payment methods.
```

2022-02-09 20:48 UTC, crookedneighbor approved these changes

2022-02-10 14:14 UTC, merged